# デプロイの設定を詳細に指定するためのファイルで、以下のような情報を設定可能
# ・ サービスの種類（web service、background jobなど）
# ・ 環境変数
# ・ ビルドコマンドやスタートコマンド
# ・ 自動デプロイの有無など

version: '1'
services:
  - type: web
    name: priceComparisonAppForIphone
    plan: free
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      npx playwright install chromium
    startCommand: 'gunicorn app:app'
