services:
  - name: official_prices_app
    type: web
    runtime: python
    buildCommand: ''
    startCommand: 'python app.py'
    envVars:
      - key: DATABASE_URL
        value: postgresql://official_prices_db_gop6_user:ngVU5yXdsM8AMyt0Jy2FdC2fOtfL9Rc0@dpg-ct8or1a3esus7384jdbg-a.oregon-postgres.render.com/official_prices_db_gop6
