runtime: python311
service: default

env_variables:
  BUCKET_NAME: "price-comparison-app-data"
  APP_ENV: "production"
  # Secret Managerから認証情報を取得（デプロイ時にPROJECT_IDを置換）
  GOOGLE_APPLICATION_CREDENTIALS_JSON: "projects/PROJECT_ID/secrets/gcp-credentials/versions/latest"

automatic_scaling:
  target_cpu_utilization: 0.6
  min_instances: 0
  max_instances: 1
  target_throughput_utilization: 0.6

resources:
  cpu: 0.5
  memory_gb: 0.25
  disk_size_gb: 1

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto

entrypoint: gunicorn -b :$PORT app:app --workers 1 --timeout 120 --preload
