apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: price-comparison-app
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: gcr.io/PROJECT_ID/price-comparison-app
          ports:
            - containerPort: 8080
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS_JSON
              valueFrom:
                secretKeyRef:
                  name: gcp-credentials
                  key: credentials.json
            - name: BUCKET_NAME
              value: "price-comparison-app-data"
            - name: APP_ENV
              value: "production"
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
