[phases.setup]
nixPkgs = ["python3", "nodejs", "curl"]

[phases.install]
cmds = [
  "curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py",
  "python3 get-pip.py --user",
  "python3 -m pip install --user -r backend/requirements.txt"
]

[phases.build]
cmds = [
  "chmod +x backend/build-and-copy.sh",
  "backend/build-and-copy.sh"
]

[start]
cmd = "python backend/app.py"

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1" 