[phases.setup]
nixPkgs = ["python3", "nodejs"]

[phases.install]
cmds = [
  "python3 --version",
  "python3 -m pip --version",
  "python3 -m pip install -r backend/requirements.txt"
]

[phases.build]
cmds = [
  "node --version",
  "npm --version",
  "chmod +x backend/build-and-copy.sh",
  "backend/build-and-copy.sh"
]

[start]
cmd = "python backend/app.py"

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1" 