services:
  - type: web
    name: price-comparison-app
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: ap-northeast-1
      # - key: LINE_CHANNEL_ACCESS_TOKEN
      #   sync: false
      # - key: LINE_CHANNEL_SECRET
      #   sync: false
    healthCheckPath: /health
    autoDeploy: true
