services:
  - type: web
    name: price-comparison-app
    runtime: python
    buildCommand: pip install -r requirements.txt && pip install playwright
    startCommand: gunicorn app:app --workers 1 --bind 0.0.0.0:$PORT --timeout 120 --preload
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: APP_ENV
        value: production
      - key: BUCKET_NAME
        value: price-comparison-app-data
      - key: CLOUD_RUN_ENDPOINT
        value: https://us-central1-price-comparison-app-463007.cloudfunctions.net/get-prices
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /opt/render/project/src/config/gcp/key.json
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.cache/ms-playwright
      - key: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD
        value: "1"
    healthCheckPath: /health
    autoDeploy: true
    branch: main
