services:
  - type: web
    name: price-comparison-app
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
    startCommand: |
      gunicorn app:app --workers 2 --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: ap-northeast-1
      - key: BUCKET_NAME
        value: price-comparison-app-data
      - key: CLOUD_RUN_ENDPOINT
        value: https://us-central1-price-comparison-app-463007.cloudfunctions.net/get-prices
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /opt/render/project/src/config/gcp/key.json
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.cache/ms-playwright
    healthCheckPath: /health
    autoDeploy: true
    branch: main
