app:
  debug: false
  log_level: INFO
  # secret_keyは環境変数から取得するため、ここには記載しない

scraper:
  kaitori_rudea_urls:
    - https://kaitori-rudeya.com/category/detail/183 # iPhone 16
    - https://kaitori-rudeya.com/category/detail/185 # iPhone 16 Pro
    - https://kaitori-rudeya.com/category/detail/186 # iPhone 16 Pro Max
  apple_store_url: https://www.apple.com/jp/shop/buy-iphone
  request_timeout: 60
  retry_count: 5
  user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
