name: Dependency Compatibility Check

on:
  schedule:
    - cron: '0 0 * * *'  # 毎日0時に実行
  workflow_dispatch:  # 手動実行も可能

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.13']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        continue-on-error: true

      - name: Check dependency compatibility
        if: failure()
        run: |
          echo "::warning::Dependency compatibility check failed. Please review the requirements.txt file."
          exit 1 
