name: Deploy to Render

on:
  push:
    branches:
      - main  # `main`ブランチへのプッシュをトリガー
      - ci/workflow_error_Configure-AWS-credentials # エラーが解消次第削除

env:
  AWS_REGION: ap-northeast-1

permissions:
  id-token: write
  contents: read

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      # コードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v4

      # Pythonのセットアップ
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 依存関係のインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r terraform/requirements.txt

      # Lambda関数のパッケージング
      - name: Package Lambda functions
        run: |
          cd terraform/scripts
          python package_lambda.py
          
          # ZIPファイルの存在確認
          cd ..
          for zip_file in *.zip; do
            if [ ! -f "$zip_file" ]; then
              echo "Error: Required Lambda package $zip_file is missing"
              exit 1
            fi
            
            if ! unzip -t "$zip_file" >/dev/null 2>&1; then
              echo "Error: Lambda package $zip_file is corrupted"
              exit 1
            fi
          done

      # Lambdaパッケージをアーティファクトとしてアップロード
      - name: Upload Lambda packages
        uses: actions/upload-artifact@v4
        with:
          name: lambda-packages
          path: |
            terraform/*.zip
            !terraform/terraform.*.zip
          retention-days: 1

  deploy:
    needs: package
    runs-on: ubuntu-latest
    steps:
      # コードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v4

      # Lambdaパッケージをダウンロード
      - name: Download Lambda packages
        uses: actions/download-artifact@v4
        with:
          name: lambda-packages
          path: terraform/

      # ZIPファイルの検証
      - name: Validate Lambda packages
        run: |
          cd terraform
          for zip_file in *.zip; do
            if [ ! -f "$zip_file" ]; then
              echo "Error: Required Lambda package $zip_file is missing"
              exit 1
            fi
            
            if ! unzip -t "$zip_file" >/dev/null 2>&1; then
              echo "Error: Lambda package $zip_file is corrupted"
              exit 1
            fi
          done

      # Terraformのセットアップ
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::273354647319:role/github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      # Terraformの初期化
      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init

      # Terraform構成の適用
      - name: Apply Terraform configuration
        run: |
          cd terraform
          terraform apply -auto-approve -input=false  # `input=false`を追加して自動承認

      # ZIPファイルのクリーンアップ
      - name: Cleanup ZIP files
        if: always()  # エラーが発生しても実行
        run: |
          cd lambdas
          rm -f *.zip
          cd ../terraform
          rm -f lambda_function.zip
