name: Deploy to Render

on:
  push:
    branches:
      - main  # `main`ブランチへのプッシュをトリガー

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # コードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v4

      # Terraformのセットアップ
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Terraformの初期化
      - name: Initialize Terraform
        env:
          TF_VAR_db_password: ${{ secrets.RENDER_POSTGRESQL_DB_PASSWORD }}  # GitHub Secretsからパスワードを取得
        run: terraform init

      # Terraform構成の適用
      - name: Apply Terraform configuration
        env:
          TF_VAR_db_password: ${{ secrets.RENDER_POSTGRESQL_DB_PASSWORD }}  # GitHub Secretsからパスワードを取得
        run: terraform apply -auto-approve -input=false  # `input=false`を追加して自動承認
