name: Deploy to Render

on:
  push:
    branches:
      - main  # `main`ブランチへのプッシュをトリガー

env:
  AWS_REGION: ap-northeast-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # コードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v4

      # Terraformのセットアップ
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActionsSession

      # Terraformの初期化
      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init

      # Terraform構成の適用
      - name: Apply Terraform configuration
        run: |
          cd terraform
          terraform apply -auto-approve
