name: Railway Log Monitor

on:
  schedule:
    - cron: '0 0,12 * * *'  # 0時と12時（12時間ごと）
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install requests
      - name: Install Railway CLI
        run: npm install -g @railway/cli@latest
      - name: Run Railway Log Monitor
        env:
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_USERNAME: ${{ secrets.SLACK_USERNAME }}
          SLACK_ICON_EMOJI: ${{ secrets.SLACK_ICON_EMOJI }}
        run: python railway/scripts/log_monitor.py --single-run 
