name: renovate
on:
  workflow_dispatch:
    schedule:
      # JST Runs every Saturday at 9:00 a.m.
      - cron: '0 9 ? * 6'

env:
  RENOVATE_REPOSITORIES: ${{ github.repository }}
  RENOVATE_USERNAME: ${{ github.repository_owner }}
  RENOVATE_GIT_AUTHOR: 'Renovate Bot <bot@renovateapp.com>'

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41.0.14
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_ACCESS_TOKEN }}
