name: renovate
on:
  workflow_dispatch:
    schedule:
      # JST Runs every Saturday at 9:00 a.m.
      - cron: '0 9 ? * 6'

env:
  RENOVATE_REPOSITORIES: ${{ github.repository }}
  RENOVATE_USERNAME: ${{ github.repository_owner }}
  RENOVATE_GIT_AUTHOR: 'Renovate Bot <bot@renovateapp.com>'

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate token
        id: get_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.RENOVATE_APP_ID }}
          private_key: ${{ secrets.RENOVATE_ACCESS_TOKEN }}

      - name: Output token
        env:
          TOKEN: ${{ steps.get_token.outputs.token }}
        run: |
          echo "Access Token: ${TOKEN:4}"

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41.0.18
        with:
          configurationFile: renovate.json
          token: 'x-access-token:${{ steps.get_token.outputs.token }}'
        env:
          RENOVATE_USERNAME: ${{ env.RENOVATE_USERNAME }}
          RENOVATE_GIT_AUTHOR: ${{ env.RENOVATE_GIT_AUTHOR }}
          RENOVATE_REPOSITORIES: ${{ env.RENOVATE_REPOSITORIES }}
