name: Scrape iPhone Prices

on:
  schedule:
    - cron: '0 10 * * *'  # 毎日10時に実行
    - cron: '0 22 * * *'  # 毎日22時に実行
  workflow_dispatch:  # 手動実行も可能

env:
  AWS_REGION: ap-northeast-1
  PYTHONPATH: ${{ github.workspace }}
  PYTHONUNBUFFERED: 1  # Pythonの出力バッファリングを無効化

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # タイムアウト設定

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2t64 libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libpango-1.0-0 libcairo2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install playwright
          playwright install chromium

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActionsSession

      - name: Run price scraping
        id: scrape
        continue-on-error: true  # エラーが発生しても続行
        run: |
          python scripts/price_scraping/scrape_prices.py

      - name: Send error notification
        if: steps.scrape.outcome == 'failure'
        run: |
          python scripts/price_scraping/send_error_notification.py "${{ steps.scrape.outcome }}" "${{ steps.scrape.outputs.error_message }}"
