name: Scrape iPhone Prices

on:
  schedule:
    - cron: '0 10 * * *'  # 毎日10時に実行
    - cron: '0 22 * * *'  # 毎日22時に実行
  workflow_dispatch:  # 手動実行も可能

env:
  AWS_REGION: ap-northeast-1
  PYTHONPATH: ${{ github.workspace }}
  PYTHONUNBUFFERED: 1  # Pythonの出力バッファリングを無効化

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # タイムアウト設定

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install playwright
          playwright install chromium --with-deps

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActionsSession

      - name: Run price scraping
        id: scrape
        continue-on-error: true  # エラーが発生しても続行
        run: |
          python src/scripts/scrape_prices.py

      - name: Send error notification
        if: steps.scrape.outcome == 'failure'
        run: |
          python src/scripts/send_error_notification.py "${{ steps.scrape.outcome }}" "${{ steps.scrape.outputs.error_message }}"

      - name: Run tests
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          pip install pytest pytest-cov
          pytest tests/ --cov=src --cov-report=xml

      - name: Upload coverage report
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          fail_ci_if_error: true 
