name: Scrape iPhone Prices

on:
  schedule:
    - cron: '0 */6 * * *'  # 6時間ごとに実行
  workflow_dispatch:  # 手動実行も可能

env:
  AWS_REGION: ap-northeast-1
  PYTHONPATH: ${{ github.workspace }}

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install base dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-base.txt

      - name: Install web dependencies
        run: |
          pip install -r requirements-web.txt
          playwright install chromium --with-deps

      - name: Install test dependencies
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          pip install -r requirements-test.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActionsSession

      - name: Run price scraping
        run: |
          python src/lambda_functions/get_prices_lambda/lambda_function.py

      - name: Run tests
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          pytest tests/ --cov=src --cov-report=xml

      - name: Upload coverage report
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          fail_ci_if_error: true 
