name: Scrape iPhone Prices

on:
  schedule:
    - cron: '0 10 * * *'  # 毎日10時に実行
    - cron: '0 22 * * *'  # 毎日22時に実行
  workflow_dispatch:  # 手動実行も可能

env:
  AWS_REGION: ap-northeast-1
  PYTHONPATH: ${{ github.workspace }}
  PYTHONUNBUFFERED: 1  # Pythonの出力バッファリングを無効化
  TEST_ENV: true  # テスト環境フラグ

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # タイムアウト設定

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install playwright
          playwright install chromium --with-deps

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActionsSession

      - name: Run price scraping
        id: scrape
        continue-on-error: true  # エラーが発生しても続行
        run: |
          python scripts/price_scraping/scrape_prices.py

      - name: Send error notification
        if: steps.scrape.outcome == 'failure'
        run: |
          python scripts/price_scraping/send_error_notification.py "${{ steps.scrape.outcome }}" "${{ steps.scrape.outputs.error_message }}"

      - name: Run tests
        if: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          AWS_REGION: ap-northeast-1
          TEST_ENV: true
          PYTHONPATH: ${{ github.workspace }}
          PYTHONUNBUFFERED: 1
          CONFIG_FILE: config/config.testing.yaml  # テスト用設定ファイルを指定
        run: |
          # テスト用設定ファイルの作成
          mkdir -p config
          cat > config/config.testing.yaml << 'EOL'
          app:
            debug: true
            log_level: DEBUG
            secret_key: test-secret-key-16ch

          scraper:
            kaitori_rudea_urls:
              - "https://kaitori-rudeya.com/category/detail/183"  # iPhone 16
              - "https://kaitori-rudeya.com/category/detail/185"  # iPhone 16 Pro
              - "https://kaitori-rudeya.com/category/detail/186"  # iPhone 16 Pro Max
              - "https://kaitori-rudeya.com/category/detail/205"  # iPhone 16 e
            apple_store_url: "https://www.apple.com/jp/shop/buy-iphone"
            request_timeout: 30
            retry_count: 3
            user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
          EOL
          
          # テストの実行
          pip install pytest pytest-cov pytest-asyncio
          python -m pytest tests/ --cov=src --cov-report=xml -v --tb=short

      - name: Upload coverage report
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          fail_ci_if_error: true 
